name: CustomAPI
version: ${project.version}
main: com.mysteria.customapi.CustomAPIPlugin
api-version: 1.16
authors: [ Singularity ]
depend: [ MysteriaUtils ]
softdepend: [ ProtocolLib, MysteriaSanity ]
